// Boilerplate API for connecting to ChatGPT, generated by ChatGPT

import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

// Optional: Edge runtime for low latency
export const runtime = "edge";

type RequestBody = {
  prompt?: string;
};
export interface AIResponse {
  status: number;
  error?: string;
  result?: string;
}

export async function POST(request: NextRequest) {
  try {
    const body: RequestBody = await request.json();
    const prompt = body.prompt?.trim();

    if (!prompt) {
      return NextResponse.json(
        { error: "Prompt is required" },
        { status: 400 }
      );
    }

    if (!process.env.OPENAI_API_KEY) {
      return NextResponse.json(
        { error: "OpenAI API key not configured" },
        { status: 500 }
      );
    }

    const client = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });

    const response = await client.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    const text = response.choices?.[0]?.message?.content ?? "";

    return NextResponse.json({ status: 200, result: text } as AIResponse);
  } catch (error) {
    console.error("OpenAI API error:", error);
    return NextResponse.json({ status: 500, error: "OpenAI request failed" } as AIResponse);
  }
}